# Python Statistics Fundamentals: How to Describe Your Data

In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

## <ins>Mean</ins>

In [3]:
mean_ = sum(x) / len(x)
mean_

8.7

### Statistics

In [4]:
mean_ = statistics.mean(x)
mean_

8.7

In [5]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

### NumPy

In [6]:
mean_ = np.mean(y)  # Function
mean_

8.7

In [7]:
mean_ = y.mean()  # Method
mean_

8.7

In [8]:
print(np.mean(y_with_nan))
y_with_nan.mean()

nan


nan

In [9]:
np.nanmean(y_with_nan)  # Omit NaNs

8.7

### Pandas

In [10]:
mean_ = z.mean()  # Omit NaNs by default
mean_

8.7

In [11]:
z_with_nan.mean()

8.7

## <ins>Weighted Mean</ins>

The weighted mean is very handy when you need the mean of a dataset containing items that occur with given relative frequencies.

In [12]:
0.2 * 2 + 0.5 * 4 + 0.3 * 8

4.8

In [13]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

6.95

In [14]:
wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
wmean

6.95

### NumPy

In [15]:
y, w = np.array(x), np.array(w)
wmean = np.average(y, weights=w)
wmean

6.95

## <ins>Harmonic Mean</ins>

The harmonic mean is the reciprocal of the mean of the reciprocals of all items in the dataset

In [16]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

### Statistics

In [17]:
statistics.harmonic_mean(x)

2.7613412228796843

In [18]:
statistics.harmonic_mean(x_with_nan)

nan

In [19]:
statistics.harmonic_mean([1, 0, 2])

0

statistics.harmonic_mean does not support negative values

### SciPy

In [20]:
scipy.stats.hmean(y)

2.7613412228796843

In [21]:
scipy.stats.hmean(z)

2.7613412228796843

## <ins>Geometric Mean</ins>

The geometric mean is the 𝑛-th root of the product of all 𝑛 elements 𝑥ᵢ in a dataset 𝑥

In [22]:
gmean = 1
for item in x:
    gmean *= item
gmean **= 1 / len(x)
gmean

4.677885674856041

### SciPy

In [23]:
scipy.stats.gmean(y)

4.67788567485604

In [24]:
scipy.stats.gmean(z)

4.67788567485604

## <ins>Median</ins>

In [25]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
median_

4

### Statistics

In [26]:
statistics.median(x)

4

In [27]:
statistics.median(x[:-1])

3.25

In [28]:
statistics.median_low(x[:-1])

2.5

In [29]:
statistics.median_high(x[:-1])

4

In [30]:
statistics.median(x_with_nan)

6.0

In [31]:
statistics.median_low(x_with_nan)

4

In [32]:
statistics.median_high(x_with_nan)

8.0

### NumPy

In [33]:
np.median(y)

4.0

In [34]:
np.median(y[:-1])

3.25

In [35]:
np.nanmedian(y_with_nan)  # NumPy median with NaN

4.0

In [36]:
np.nanmedian(y_with_nan[:-1])  # NumPy median with NaN

3.25

### Pandas

In [37]:
z.median()

4.0

In [38]:
z_with_nan.median()

4.0

## <ins>Mode<ins>

In [39]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

### Statistics

In [40]:
statistics.mode(u)

2

In [41]:
statistics.mode([2, math.nan, 2])

2

In [42]:
statistics.mode([2, math.nan, 0, math.nan, 5])

nan

statistics.multimode() is introduced in Python 3.8.

### SciPy

In [43]:
u, v = np.array(u), np.array(v)

In [44]:
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [45]:
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

In [46]:
scipy.stats.mode(v).mode

array([12])

In [47]:
scipy.stats.mode(v).count

array([3])

### Pandas

In [48]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [49]:
u.mode()

0    2
dtype: int32

In [50]:
v.mode()

0    12
1    15
dtype: int32

In [51]:
w.mode()

0    2.0
dtype: float64

## <ins>Variance</ins>

In [52]:
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

### Statistics

In [53]:
statistics.variance(x)

123.2

In [54]:
statistics.variance(x_with_nan)

nan

### NumPy

In [55]:
np.var(y_with_nan, ddof=1)

nan

In [56]:
y_with_nan.var(ddof=1)

nan

In [57]:
np.nanvar(y_with_nan, ddof=1)

123.19999999999999

### Pandas

In [58]:
z.var(ddof=1)

123.19999999999999

In [59]:
z_with_nan.var(ddof=1)

123.19999999999999

## <ins>Standard Deviation</ins>

In [60]:
std_ = var_ ** 0.5
std_

11.099549540409285

### Statistics

In [61]:
statistics.stdev(x)

11.099549540409287

### NumPy

In [62]:
np.std(y, ddof=1)

11.099549540409285

In [63]:
y.std(ddof=1)

11.099549540409285

In [64]:
np.std(y_with_nan, ddof=1)

nan

In [65]:
y_with_nan.std(ddof=1)

nan

In [66]:
np.nanstd(y_with_nan, ddof=1)

11.099549540409285

### Pandas

In [67]:
z.std(ddof=1)

11.099549540409285

In [68]:
z_with_nan.std(ddof=1)

11.099549540409285

## <ins>Skewness</ins>

skewness measures the asymmetry of a data sample

In [69]:
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
std_ = var_ ** 0.5
skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.9470432273905929

### SciPy

In [70]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [71]:
scipy.stats.skew(y_with_nan, bias=False)

nan

### Pandas

In [72]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
z.skew()

1.9470432273905924

In [73]:
z_with_nan.skew()

1.9470432273905924

## <ins>Percentiles</ins>

In [74]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

### NumPy

In [75]:
y = np.array(x)
np.percentile(y, 5)

-3.44

In [76]:
np.percentile(y, 95)

34.919999999999995

In [77]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [78]:
np.median(y)

8.0

In [79]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [80]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [81]:
np.quantile(y, 0.05)

-3.44

In [82]:
np.quantile(y, 0.95)

34.919999999999995

In [83]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [84]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

### Pandas

In [85]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-3.44

In [86]:
z.quantile(0.95)

34.919999999999995

In [87]:
z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [88]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

## <ins>Ranges</ins>

In [89]:
np.ptp(y)

46.0

In [90]:
np.ptp(z)

46.0

In [91]:
np.ptp(y_with_nan)

nan

In [92]:
np.ptp(z_with_nan)

nan

In [93]:
np.amax(y) - np.amin(y)

46.0

In [94]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [95]:
y.max() - y.min()

46.0

In [96]:
z.max() - z.min()

46.0

In [97]:
z_with_nan.max() - z_with_nan.min()

46.0

In [99]:
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [100]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

## <ins>Summary of Descriptive Statistics</ins>